version: "3"

services:
  mariadb:
    image: mysql:5.7

    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    ports:
      - ${DB_PORT}:3306
    volumes:
    # By default, there is the latest version of the application already present in the container
    # If you want to provider the container with your own .war file, uncomment the following line
    - ./bd:/bd
